# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZJ2Jb_med-kCc8L74klSeTq3lBnT4O3
"""

import yaml

with open('DeepDTI.yml', 'w') as filename:
    model_configuration = dict(protein_in_dim=26,
                           protein_embedding_dim=20,
                           protein_max_seq_length=2500,
                           protein_filter_size=128,
                           protein_kernel_sizes=[10, 15, 20, 25, 30],
                           protein_dense_out_dim=128,
                           drug_max_seq_length=2048,
                           drug_hidden_dims=[512, 128],
                           fc_out_dim=128,
                           num_class=1)
    
    train_loader_kwargs = dict(batch_size=256,
                               pin_memory=True)
    val_loader_kwargs = dict(batch_size=256,
                             pin_memory=True)
    
    trainer_kwargs = dict(gpus=1,
                          #distributed_backend="dp",  # multiple-gpus, 1 machine
                          max_epochs=100,
                          benchmark=False,
                          deterministic=True,
                          #callbacks=callbacks,
                          #accumulate_grad_batches=2,
                          #checkpoint_callback=checkpoint_callback,
                          gradient_clip_val=1,
                          #precision=16,
                          #logger=logger,
                          progress_bar_refresh_rate = 4)
    
    dataset_kwargs = {"mode": "train"}

    config = {"dataset_signature": "DeepConvDTIDataset",
              "dataset_index_file_format": "{}_indices.csv",
              #"dataset_path": dataset_path,
              "dataset_kwargs": dataset_kwargs,
              "model_kwargs": model_configuration,
              "train_loader_kwargs": train_loader_kwargs,
              "val_loader_kwargs": val_loader_kwargs,
              "trainer_kwargs": trainer_kwargs,
              "predefined_folds": True,
              "seed": 42,
              "model_signature": "DeepConvDTI",
              "checkpoint_path": "models",
              }

    yaml.dump(config, filename)

with open('DeepDTA.yml', 'w') as filename:
    model_configuration = dict(drug_in_dim=66,
                              drug_convolution_filter_sizes=[32, 64, 96],
                              drug_convolution_kernel_sizes=[4, 6, 8],
                              drug_convolution_out_dim=96,
                              drug_out_dim=256,
                              drug_sequence_max_length=100,
                              drug_embedding_dim=128,
                              protein_in_dim=26,
                              protein_convolution_filter_sizes=[32, 64, 96],
                              protein_convolution_kernel_sizes=[4, 8, 12],
                              protein_convolution_out_dim=96,
                              protein_out_dim=256,
                              protein_sequence_max_length=1000,
                              protein_embedding_dim=128,
                              fully_connected_dimensions=[1024, 1024, 512],
                              num_class=1)
    
    train_loader_kwargs = dict(batch_size=256,
                               pin_memory=True)
    val_loader_kwargs = dict(batch_size=256,
                             pin_memory=True)
    
    trainer_kwargs = dict(gpus=1,
                          #distributed_backend="dp",  # multiple-gpus, 1 machine
                          max_epochs=100,
                          benchmark=False,
                          deterministic=True,
                          #callbacks=callbacks,
                          #accumulate_grad_batches=2,
                          #checkpoint_callback=checkpoint_callback,
                          gradient_clip_val=1,
                          #precision=16,
                          #logger=logger,
                          progress_bar_refresh_rate = 4)
    
    dataset_kwargs = {"mode": "train"}

    config = {"dataset_signature": "DeepDTADataset",
              "dataset_index_file_format": "{}_indices.csv",
              "dataset_kwargs": dataset_kwargs,
              "model_kwargs": model_configuration,
              "train_loader_kwargs": train_loader_kwargs,
              "val_loader_kwargs": val_loader_kwargs,
              "trainer_kwargs": trainer_kwargs,
              "predefined_folds": True,
              "seed": 42,
              "model_signature": "DeepDTA",
              "checkpoint_path": "models",
              }

    yaml.dump(config, filename)

